name: 'Create Pull Request'
description: 'Creates a pull request for syncing with web-shim-codegen'

inputs:
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  package_version:
    description: 'Package version to include in PR title'
    required: true
  base:
    description: 'Base branch for the PR'
    required: false
    default: 'main'
  head:
    description: 'Head branch for the PR'
    required: false
    default: 'cd_update'
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        script: |
          await github.rest.pulls.create({
            owner: '${{ inputs.owner }}',
            repo: '${{ inputs.repo }}',
            title: 'ci: sync with web-shim-codegen v' + '${{ inputs.package_version }}',
            body: 'This update was generated by the GitHub CD action.',
            base: '${{ inputs.base }}',
            head: '${{ inputs.head }}'
          });
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
