#!/bin/bash

set -euo pipefail

function bootstrap_macos() {
  # ensure we have homebrew installed
  if ! command -v brew &> /dev/null; then
    echo "You must install homebrew to install the dependencies."
    exit 1
  fi

  echo "updating brew"
  brew update
}


function bootstrap_linux() {
  if ! command -v sudo &> /dev/null; then
      echo "Please install sudo before running this script"
      exit
  fi

  echo "updating apt"
  sudo apt update
}

if [[ "$(uname)" = "Darwin" ]]; then
  bootstrap_macos
elif [[ "$(uname)" = "Linux" ]]; then
  bootstrap_linux
fi

echo "installing yellicode generator"
npm install @yellicode/cli -g

yarn add eslint --dev
