#!/bin/bash

set -euo pipefail

function bootstrap_macos() {
  # ensure we have homebrew installed
  if ! command -v brew &> /dev/null; then
    echo "You must install homebrew to install the dependencies."
    exit 1
  fi

  echo "updating brew"
  brew update

  echo "installing nvm"
  brew install nvm
}

function bootstrap_linux() {
  if ! command -v sudo &> /dev/null; then
      echo "Please install sudo before running this script"
      exit
  fi

  echo "updating apt"
  sudo apt update

  if ! command -v nvm &> /dev/null; then
    # Unfortunately there's no easy link to latest release. We'll have to update
    # this link if we want a newer version of nvm.
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
  fi
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

if [[ "$(uname)" = "Darwin" ]]; then
  bootstrap_macos
elif [[ "$(uname)" = "Linux" ]]; then
  bootstrap_linux
fi

echo "installing node"
nvm install `cat .nvmrc`
nvm use `cat .nvmrc`
