#!/bin/bash
set -euo pipefail

# Fixes the following error when "yarn build" is run
#   You must provide the URL of lib/mappings.wasm
export NODE_OPTIONS=--no-experimental-fetch

bold=$(tput bold)
normal=$(tput sgr0)

log() {
  echo -e "\n${bold}$1${normal}"
}

cleanup() {
  rm -rf build ts-to-es6 dist
  mkdir -p {build,dist}/vue
}

log "🔍 Linting"
npm run lint

log "🧹 Cleanup"
cleanup

log "🧵 Transpiling"
tsc

log "⚡️ Code generation"
yellicode

log '🧶 Bundling Angular SDK'
(cd src/scaffolds/angular-workspace &&
  npm i &&
  npm run build -- --configuration=production &&
  cp -R dist/onesignal-ngx ../../../build)

log "📄 Copying static files"
./scripts/copy-static

log "📦 Archiving"
tar cfz dist/onesignal-ngx.tgz build/onesignal-ngx &
tar cfz dist/react.tgz build/react &
tar cfz dist/vue/v2.tgz build/vue/v2 &
tar cfz dist/vue/v3.tgz build/vue/v3

# This is required to use 'npm link' when testing local builds
# We do this last so unneed files are not included in the releases.
log '👀 Install and Linting'
concurrently --kill-others-on-fail "npm ci --loglevel=error --prefix=build/vue/v3" "npm ci --loglevel=error --prefix=build/vue/v2" "npm ci --loglevel=error --prefix=build/react" "npm i --prefix=build/onesignal-ngx"

log '✅ Done!'
