#!/bin/bash

set -euo pipefail

# Fixes the following error when "yarn build" is run
#   You must provide the URL of lib/mappings.wasm
export NODE_OPTIONS=--no-experimental-fetch

echo "Linting..."
npm run lint
echo 'Done.'

echo "Cleanup..."
rm -rf build
rm -rf ts-to-es6
echo 'Done.'

mkdir -p dist/vue

echo "Transpiling..."
tsc
echo 'Done.'

echo "Code-generation initiating..."
yellicode
echo 'Done.'

echo 'Bundling Angular SDK...'
cd src/scaffolds/angular-workspace
npm install && npm run build -- --configuration=production
cp -R dist/onesignal-ngx ../../../build
cd ../../../
echo 'Done.'

echo 'Copying static files...'
./scripts/copy-static
echo 'Done.'

echo 'Downstream repos setup.'
cd build
echo 'Archiving...'
tar cvfz onesignal-ngx.tgz onesignal-ngx
tar cvfz react.tgz react
tar cvfz vue/v2.tgz vue/v2
tar cvfz vue/v3.tgz vue/v3
echo 'Done.'
cd ..

echo 'Moving build files...'
mv build/onesignal-ngx.tgz dist/onesignal-ngx.tgz
mv build/react.tgz dist/react.tgz
mv build/vue/v2.tgz dist/vue/v2.tgz
mv build/vue/v3.tgz dist/vue/v3.tgz
echo 'Done.'

# This is required to use 'npm link' when testing local builds
# We do this last so unneed files are not included in the releases.
echo 'npm init for local dev testing'

echo 'npm init Vue3...'
cd build/vue/v3
npm install
cd ../../../

echo 'npm init Vue2...'
cd build/vue/v2
npm install
cd ../../../

echo 'npm init react...'
cd build/react
npm install
cd ../../

echo 'npm init ngx...'
cd build/onesignal-ngx
npm install
cd ../../
