#!/bin/bash

shopt -s nullglob dotglob

paths=("onesignal-ngx" "react" "vue/v2" "vue/v3")

copy_if_any() {
  local flags=$1; shift
  local dest=$1; shift
  local files=("$@")
  if [ ${#files[@]} -gt 0 ]; then
    rsync -q $flags --exclude=node_modules "${files[@]}" "$dest"
  fi
}

for tgt in "${paths[@]}"; do
  shared_visible=(src/static/*)
  shared_hidden=(src/static/.[^.]*)
  proj_visible=(src/static/$tgt/*)
  proj_hidden=(src/static/$tgt/.[^.]*)

  copy_if_any "-t"  "build/$tgt/" "${shared_visible[@]}"
  copy_if_any "-tr" "build/$tgt/" "${shared_hidden[@]}"
  copy_if_any "-tr" "build/$tgt/" "${proj_visible[@]}"
  copy_if_any "-tr" "build/$tgt/" "${proj_hidden[@]}"
done
