#!/bin/bash
set -euo pipefail

# Usage: patch-repo.sh <tar-file> <target-directory> <repo-name>
# Example: patch-repo.sh dist/react.tgz __clone/react react-onesignal
# Requires PACKAGE_VERSION environment variable to be set

if [ $# -lt 3 ]; then
  echo "Usage: $0 <tar-file> <target-directory> <repo-name>"
  exit 1
fi

TAR_FILE="$1"
TARGET_DIR="$2"
REPO_NAME="$3"
VERSION="${PACKAGE_VERSION:-unknown}"

if [ ! -f "$TAR_FILE" ]; then
  echo "Error: Tar file $TAR_FILE does not exist"
  exit 1
fi

if [ ! -r "$TAR_FILE" ]; then
  echo "Error: Tar file $TAR_FILE is not readable"
  exit 1
fi

if [ ! -d "$TARGET_DIR" ]; then
  echo "Error: Target directory $TARGET_DIR does not exist"
  exit 1
fi

# Verify tar file is valid before proceeding
if ! tar -tzf "$TAR_FILE" >/dev/null 2>&1; then
  echo "Error: Tar file $TAR_FILE is corrupted or invalid"
  exit 1
fi

# Determine how many leading components to strip from the tarball
# We count the number of directory separators in the first entry
# e.g., "vue/v2/" -> 2 slashes -> strip 2, "react/" -> 1 slash -> strip 1
# Use a temporary file to avoid broken pipe errors when piping tar output
TEMP_LIST=$(mktemp)
trap "rm -f $TEMP_LIST" EXIT
if ! tar -tf "$TAR_FILE" > "$TEMP_LIST" 2>/dev/null; then
  echo "Error: Could not read tar file $TAR_FILE"
  exit 1
fi
FIRST_ENTRY=$(head -n 1 "$TEMP_LIST")
if [ -z "$FIRST_ENTRY" ]; then
  echo "Error: Tar file $TAR_FILE appears to be empty"
  exit 1
fi
STRIP_COMPONENTS=$(echo "$FIRST_ENTRY" | tr -cd '/' | wc -c)
rm -f "$TEMP_LIST"
trap - EXIT

# Clean up target directory except for .git, node_modules, CHANGELOG.md, and package-lock.json to ensure a clean sync
# CHANGELOG.md is preserved because it's generated by semantic-release, not included in the tarball
# package-lock.json is preserved as a defensive measure, even though it should be in the tarball
# This allows 'git add -A' to detect deletions
find "$TARGET_DIR" -mindepth 1 -maxdepth 1 ! -name ".git" ! -name "node_modules" ! -name "CHANGELOG.md" ! -name "package-lock.json" -exec rm -rf {} +

# Extract tar archive directly into the target directory, stripping the prefix
# Use explicit error handling to catch any extraction failures
if ! tar zxf "$TAR_FILE" -C "$TARGET_DIR" --strip-components="${STRIP_COMPONENTS// /}"; then
  echo "Error: Failed to extract tar file $TAR_FILE to $TARGET_DIR"
  exit 1
fi

# Add all changes and commit
cd "$TARGET_DIR"
git add -A
if git commit -m "build: sync with web-shim-codegen v$VERSION"; then
  echo "$REPO_NAME repository has been updated"
else
  echo "$REPO_NAME repository has NOT been updated, no changes to commit"
fi

